# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebdc6c839145de2da5d2019b9e8ae68e420d7c52ac14358f9f49f9e9458df86276dec178b36cacc2e15c278b683fb56beb6c0b48b78b2fbd9a72e7a91746a497

test:
  secret_key_base: 0ced997cb8662be37ed797b2f5dfec542a56ceb71e42a4e5f0fc1a794ab6dc9b813e246f5ef117031d3a43ca39521819dfded2fb24382f541a9b37cc0b6ebdb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
